author: 'iAtog'
name: 'CharacterDialogue'
version: 0.8
api-version: 1.16
depend: [ Citizens ]
softdepend: [ PlaceHolderAPI, HolographicDisplays ]
main: me.iatog.characterdialogue.CharacterDialoguePlugin